---
- name: Check kube-apiserver
  become: false
  shell: |
    echo $(kubectl get pods -n kube-system | grep kube-apiserver | awk '{ print $3 }')
  register: kube_status
  until: kube_status.stdout == "Running"
  retries: 15
  delay: 30

- name: Patch loadbalancer svc external ip
  become: false
  shell: |
    kubectl patch svc ingress-nginx-controller -p '{"spec":{"loadBalancerIP":"{{ ingress_nginx_private_ip }}"}}' -n ingress-nginx
  ignore_errors: yes
